{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6c64ea3d-36d7-4736-af79-e8fce902fa99",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "from sklearn.ensemble import RandomForestRegressor\n",
    "\n",
    "# -------------------------------\n",
    "# Page configuration\n",
    "# -------------------------------\n",
    "st.set_page_config(page_title=\"Zimbabwe Aircraft Movements Forecast Dashboard\",\n",
    "                   layout=\"wide\")\n",
    "\n",
    "st.title(\"✈️ Zimbabwe Aircraft Movements Forecast Dashboard\")\n",
    "st.markdown(\"This dashboard uses an **Improved Random Forest model with engineered time-series features** to generate a 10‑year forecast of aircraft movements.\")\n",
    "\n",
    "# -------------------------------\n",
    "# Load & Prepare Data\n",
    "# -------------------------------\n",
    "df = pd.read_csv(\"Monthly_Expanded_WholeNumbers.csv\")\n",
    "df['Date'] = pd.to_datetime(df[['Year', 'Month']].assign(DAY=1))\n",
    "df = df.sort_values(\"Date\")\n",
    "\n",
    "# -------------------------------\n",
    "# Feature Engineering\n",
    "# -------------------------------\n",
    "df[\"Month\"] = df[\"Date\"].dt.month\n",
    "df[\"YearVal\"] = df[\"Date\"].dt.year\n",
    "df[\"TimeIndex\"] = np.arange(len(df))\n",
    "df[\"Lag1\"] = df[\"Total\"].shift(1)\n",
    "df[\"Lag12\"] = df[\"Total\"].shift(12)\n",
    "df[\"Rolling3\"] = df[\"Total\"].rolling(3).mean()\n",
    "df[\"Rolling12\"] = df[\"Total\"].rolling(12).mean()\n",
    "df = df.dropna()\n",
    "\n",
    "features = [\"TimeIndex\", \"Month\", \"YearVal\", \"Lag1\", \"Lag12\", \"Rolling3\", \"Rolling12\"]\n",
    "X = df[features]\n",
    "y = df[\"Total\"]\n",
    "\n",
    "# -------------------------------\n",
    "# Train the Model\n",
    "# -------------------------------\n",
    "model = RandomForestRegressor(n_estimators=500, random_state=42)\n",
    "model.fit(X, y)\n",
    "\n",
    "# -------------------------------\n",
    "# Forecast Next 10 Years (120 months)\n",
    "# -------------------------------\n",
    "future_rows = 120\n",
    "last = df.iloc[-1]\n",
    "future_data = []\n",
    "\n",
    "for i in range(1, future_rows + 1):\n",
    "    e = {}\n",
    "    e[\"TimeIndex\"] = last[\"TimeIndex\"] + i\n",
    "    e[\"Month\"] = ((int(last[\"Month\"]) + i - 1) % 12) + 1\n",
    "    e[\"YearVal\"] = int(last[\"YearVal\"]) + ((int(last[\"Month\"]) + i - 1) // 12)\n",
    "    e[\"Lag1\"] = df[\"Total\"].iloc[-1] if i == 1 else future_data[-1][\"Forecast\"]\n",
    "\n",
    "    if i <= 12:\n",
    "        e[\"Lag12\"] = df[\"Total\"].iloc[-12 + i]\n",
    "    else:\n",
    "        e[\"Lag12\"] = future_data[-12 + i][\"Forecast\"]\n",
    "\n",
    "    e[\"Rolling3\"] = np.mean([e[\"Lag1\"], e[\"Lag12\"], df[\"Total\"].iloc[-1]])\n",
    "    e[\"Rolling12\"] = df[\"Rolling12\"].iloc[-1]\n",
    "    future_data.append(e)\n",
    "\n",
    "future_df = pd.DataFrame(future_data)\n",
    "future_df[\"Forecast\"] = model.predict(future_df[features])\n",
    "\n",
    "# Generate forecast dates\n",
    "future_dates = pd.date_range(df[\"Date\"].iloc[-1], periods=121, freq=\"M\")[1:]\n",
    "future_df[\"Date\"] = future_dates\n",
    "\n",
    "# -------------------------------\n",
    "# Dashboard Layout\n",
    "# -------------------------------\n",
    "st.subheader(\"📊 Historical vs Forecasted Aircraft Movements\")\n",
    "\n",
    "fig, ax = plt.subplots(figsize=(14, 6))\n",
    "ax.plot(df[\"Date\"], df[\"Total\"], label=\"Historical Data\")\n",
    "ax.plot(future_df[\"Date\"], future_df[\"Forecast\"], label=\"Forecast (Next 10 Years)\")\n",
    "ax.set_title(\"10-Year Forecast of Total Aircraft Movements\")\n",
    "ax.set_xlabel(\"Date\")\n",
    "ax.set_ylabel(\"Movements\")\n",
    "ax.legend()\n",
    "st.pyplot(fig)\n",
    "\n",
    "st.subheader(\"📄 Forecast Data Table\")\n",
    "st.dataframe(future_df[[\"Date\", \"Forecast\"]])\n",
    "\n",
    "# Offer CSV Download\n",
    "st.download_button(\n",
    "    label=\"Download Forecast as CSV\",\n",
    "    data=future_df.to_csv(index=False),\n",
    "    file_name=\"10_year_aircraft_movement_forecast.csv\",\n",
    "    mime=\"text/csv\"\n",
    ")\n",
    "\n",
    "st.info(\"Dashboard generated using engineered features: Month, Year, TimeIndex, Lag1, Lag12, Rolling3, Rolling12.\")\n",
    "``"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
